"""add leads table

Revision ID: 0314dec8152f
Revises: ec51d040d3ed
Create Date: 2026-08-09 17:19:46.541957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0314dec8152f'
down_revision: Union[str, Sequence[str], None] = 'ec51d040d3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abn', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gst_status', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('positive_signals', sa.Text(), nullable=True),
    sa.Column('negative_signals', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('buyer_type', sa.String(length=100), nullable=True),
    sa.Column('import_activity', sa.String(length=50), nullable=True),
    sa.Column('india_sourcing', sa.String(length=50), nullable=True),
    sa.Column('bulk_buyer', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abn', name='uq_leads_abn')
    )
    op.create_index(op.f('ix_leads_abn'), 'leads', ['abn'], unique=False)
    op.create_index(op.f('ix_leads_classification'), 'leads', ['classification'], unique=False)
    op.create_index(op.f('ix_leads_company_name'), 'leads', ['company_name'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_lead_score'), 'leads', ['lead_score'], unique=False)
    op.create_index(op.f('ix_leads_state'), 'leads', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_state'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_score'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_classification'), table_name='leads')
    op.drop_index(op.f('ix_leads_abn'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
