"""add distributor metadata

Revision ID: 89c4fa6ead6b
Revises: 2a35ae3008d0
Create Date: 2026-08-08 11:45:05.666936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c4fa6ead6b'
down_revision: Union[str, Sequence[str], None] = '2a35ae3008d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('source', sa.String(length=255), nullable=True))
    op.add_column('distributors', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('distributors', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributors', 'notes')
    op.drop_column('distributors', 'verification_status')
    op.drop_column('distributors', 'source')
    # ### end Alembic commands ###
