"""add distributor intelligence fields

Revision ID: ec51d040d3ed
Revises: 89c4fa6ead6b
Create Date: 2026-08-08 14:24:31.857272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec51d040d3ed'
down_revision: Union[str, Sequence[str], None] = '89c4fa6ead6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributors', sa.Column('product', sa.String(length=255), nullable=True))
    op.add_column('distributors', sa.Column('buyer_type', sa.String(length=100), nullable=True))
    op.add_column('distributors', sa.Column('import_activity', sa.String(length=50), nullable=True))
    op.add_column('distributors', sa.Column('india_sourcing', sa.String(length=50), nullable=True))
    op.add_column('distributors', sa.Column('bulk_buyer', sa.String(length=50), nullable=True))
    op.add_column('distributors', sa.Column('last_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distributors', 'last_verified_at')
    op.drop_column('distributors', 'bulk_buyer')
    op.drop_column('distributors', 'india_sourcing')
    op.drop_column('distributors', 'import_activity')
    op.drop_column('distributors', 'buyer_type')
    op.drop_column('distributors', 'product')
    # ### end Alembic commands ###
